paths:
  .github/workflows/*.{yml,yaml}:
    ignore:
      - 'specifying action ".+" in invalid format because owner and repo and ref should not be empty. available formats are "{owner}/{repo}@{ref}" or "{owner}/{repo}/{path}@{ref}"'